# This is a basic workflow to help you get started with Actions 0389905577

name: vietsub_build

on:
  workflow_dispatch:
    inputs:
     ROM_URL:
      description: 'OTA Url'
      required: true
      default: 'Paste Link ROM here'
  
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@v2
       
       - name: Setting up
         run: |
            sudo apt-get install -y git wget zip unzip axel
            
       - name: Set up Rclone 
         run: |
             cd $GITHUB_WORKSPACE
             curl https://rclone.org/install.sh | sudo bash
             cp rclone.conf ~/
             mkdir ~/.config/rclone/
             cp rclone.conf ~/.config/rclone/
       - name: Download ROM
         run: |
            cd $GITHUB_WORKSPACE
            axel -n $(nproc) ${{ github.event.inputs.ROM_URL }} 
           
       - name: Debloating .... 
         run: |
            cd $GITHUB_WORKSPACE
            sudo chmod 777 -R *
            ./split.sh
            
       - name: Upload First File
         run: |
            cd $GITHUB_WORKSPACE
            rclone copy $(ls | grep "1_miui") onedrive:/SPLIT_MIUI/
       - name: Upload Second File
         run: |
            cd $GITHUB_WORKSPACE
            rclone copy $(ls | grep "2_miui") onedrive:/SPLIT_MIUI/
